/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Exceptions.ComprobanteDirectorioException;
import Exceptions.ComprobanteYaExisteException;
import Exceptions.DatosLicenciaException;
import Exceptions.DatosTitularException;
import Gestores.GestorArchivos;
import Gestores.GestorDomicilio;
import Gestores.GestorLicencias;
import Gestores.GestorSesion;
import Gestores.GestorTitular;
import Modelo.Licencia;
import Modelo.Titular;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTextField;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Julian
 */
public class EmitirLicencia extends javax.swing.JFrame {

    Titular tit;

    public Titular getTit() {
        return tit;
    }

    /**
     * Creates new form EmitirLicencia
     */
    public EmitirLicencia(Titular tit) {
        this.tit = tit;
        initComponents();
        
        /*Generamos en primera instancia una nueva licencia (sin guardar)
        para que se calcule su fecha de caducidad y el costo, usando los datos
        ya existentes de titular y clase. Se setean donde corresponda.
        */
        Licencia lic = null;
        try {
            lic = GestorLicencias.crearLicencia(this.getTit(), GestorSesion.getUsuarioActual(), (String) this.getClaseCombo().getSelectedItem());
        } catch (DatosLicenciaException ex) {
            Logger.getLogger(EmitirLicencia.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.getCostoText().setText(((Float) lic.getCosto()).toString());
        this.getExpiracionText().setText(lic.getFechaExpiracion().toString());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emitirLicenciaLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        costoText = new javax.swing.JTextField();
        imprimirButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        claseCombo = new javax.swing.JComboBox<>();
        expiracionText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        emitirLicenciaLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        emitirLicenciaLabel.setText("EMITIR LICENCIA");

        nombreLabel.setText("Clase:");

        jLabel1.setText("Fecha de expiración:");

        dniLabel.setText("Costo:");

        costoText.setEditable(false);

        imprimirButton.setText("Imprimir Comprobante");
        imprimirButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imprimirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirButtonActionPerformed(evt);
            }
        });

        jButton4.setText("Volver");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        claseCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "E", "G" }));
        claseCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                claseComboItemStateChanged(evt);
            }
        });
        claseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseComboActionPerformed(evt);
            }
        });

        expiracionText.setEditable(false);
        expiracionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiracionTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dniLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(costoText))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emitirLicenciaLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imprimirButton)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(expiracionText))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(claseCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(emitirLicenciaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(claseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(expiracionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniLabel)
                    .addComponent(costoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imprimirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imprimirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirButtonActionPerformed

        Licencia lic = null;
        try {
            lic = GestorLicencias.crearLicencia(this.getTit(), GestorSesion.getUsuarioActual(), (String) this.getClaseCombo().getSelectedItem());
        } catch (DatosLicenciaException ex) {
            Logger.getLogger(EmitirLicencia.class.getName()).log(Level.SEVERE, null, ex);
        }
        GestorDomicilio.guardarDomicilio(tit.getDomicilio());
        GestorTitular.guardarTitular(tit);
        GestorLicencias.guardarLicencia(lic);

        try {
            GestorArchivos.imprimir(lic);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(EmitirLicencia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ComprobanteYaExisteException ex) {
            Logger.getLogger(EmitirLicencia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ComprobanteDirectorioException ex) {
            Logger.getLogger(EmitirLicencia.class.getName()).log(Level.SEVERE, null, ex);
        }

        File escritorioDelUsuario = FileSystemView.getFileSystemView().getHomeDirectory();

        showMessageDialog(null, "Se guardó el archivo extosamente en " + escritorioDelUsuario.getAbsolutePath().toString() + "\\Comprobantes");

        this.dispose();


    }//GEN-LAST:event_imprimirButtonActionPerformed

    private void expiracionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiracionTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiracionTextActionPerformed

    private void claseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claseComboActionPerformed

    private void claseComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_claseComboItemStateChanged
        //TODO: Crear el objeto licencia para calcular el costo y setear según el cambio de clase

        Licencia lic = null;
        try {
            lic = GestorLicencias.crearLicencia(this.getTit(), GestorSesion.getUsuarioActual(), (String) this.getClaseCombo().getSelectedItem());
        } catch (DatosLicenciaException ex) {
            Logger.getLogger(EmitirLicencia.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.getCostoText().setText(((Float) lic.getCosto()).toString());
        this.getExpiracionText().setText(lic.getFechaExpiracion().toString());

    }//GEN-LAST:event_claseComboItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (GestorSesion.getUsuarioActual().isEsAdministrador()) {
            MenuAdmin menu = new MenuAdmin();
            menu.setVisible(true);
            this.dispose();
        } else {
            MenuOperario menu = new MenuOperario();
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    public JTextField getExpiracionText() {
        return expiracionText;
    }

    public JTextField getCostoText() {
        return costoText;
    }

    public JComboBox<String> getClaseCombo() {
        return claseCombo;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> claseCombo;
    private javax.swing.JTextField costoText;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JLabel emitirLicenciaLabel;
    private javax.swing.JTextField expiracionText;
    private javax.swing.JButton imprimirButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombreLabel;
    // End of variables declaration//GEN-END:variables
}
